services:
  db:
    image: postgres:17-alpine
    container_name: auth-service_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-auth}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-strongpassword1*}
      POSTGRES_DB: ${POSTGRES_DB:-authDB}
    ports:
      # Secure: Only allows connections from your local machine, not the open internet
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  auth:
    build: .
    container_name: auth-service
    restart: unless-stopped
    ports:
      # Assuming 50051 for gRPC. Adjust if needed.
      - "${PORT:-50051}:${PORT:-50051}"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
